### ISSUE TITLE
Add logger

### ISSUE THREAD

**Issue by ueda0319** [ueda0319/neddf#17]
## Why

To use Tensorboard logger

## Definition of Done

Tensorboard viewer run collectly

**Comment by ueda0319** [comment]
importing SummaryWrite is failed as following errors:
```
challenger@0db475fe6eaa:~/neddf$ poetry run python neddf/scripts/run.py 
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.11) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "neddf/scripts/run.py", line 11, in <module>
    from neddf.trainer import NeRFTrainer
  File "/home/challenger/neddf/neddf/trainer/__init__.py", line 1, in <module>
    from neddf.trainer.nerf_trainer import NeRFTrainer  # noqa
  File "/home/challenger/neddf/neddf/trainer/nerf_trainer.py", line 18, in <module>
    from neddf.logger import NeRFTBLogger
  File "/home/challenger/neddf/neddf/logger/__init__.py", line 2, in <module>
    from neddf.logger.nerf_tb_logger import NeRFTBLogger  # noqa
  File "/home/challenger/neddf/neddf/logger/nerf_tb_logger.py", line 3, in <module>
    from torch.utils.tensorboard import SummaryWriter
  File "/home/challenger/neddf/.venv/lib/python3.8/site-packages/torch/utils/tensorboard/__init__.py", line 4, in <module>
    LooseVersion = distutils.version.LooseVersion
AttributeError: module 'distutils' has no attribute 'version'
```

**Comment by ueda0319** [comment]
This looks issue of setuptool version
https://twitter.com/hpp_ricecake/status/1488496361096249355

`poetry run pip install -U pip 'setuptools==59.5.0'` solve the problem.
